### PR TITLE
django_rest_api

### PR DESCRIPTION
**Pull request by Sushi22**
token authentication api

### CODE REVIEW

**Comment by Rits1272** [comment]
Hey @Sushi22! Excellent work. I think that you have made the **login api** but not the register one. Please make an api for **registration** too.

**Comment by Rits1272** [comment]
Also please make a **gitignore** file and add *.pyc* in it. So git will ignore all files having .pyc extension.

**Comment by Sushi22** [comment]
> Also please make a **gitignore** file and add _.pyc_ in it. So git will ignore all files having .pyc extension.

okay....i will..

**Comment by Sushi22** [comment]
> Hey @Sushi22! Excellent work. I think that you have made the login api but not the register one. Please make an api for registration too.

Sure ..... : )

**Pull request closed without merging**
