### PR TITLE
django_rest_api(modified)

### PR DESCRIPTION
**Pull request by Sushi22**
this is an api for user registration,login,logout as well as for list of all users.

### CODE REVIEW

**Comment by Rits1272** [comment]
Great work! 'll review ASAP

**Comment by Rits1272** [comment]
Hey @Sushi22! Your code is working fine. But you were supposed to make changes in the backend folder. But here you created an entire new folder. From next time please make changes in the backend folder :)

**Comment by Rits1272** [comment]
Please also update requirements file

**Comment by Sushi22** [comment]
thank u @Rits1272 i will surely take care of what u said from next time.

**Pull request merged**
